apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy10
  labels:
    app: autodeploy10
  namespace: namespace-workflow-1700644042282
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy10
  template:
    metadata:
      labels:
        app: autodeploy10
    spec:
      containers:
        - name: autodeploy10
          image: acrworkflow1700644042282.azurecr.io/image-workflow-1700644042282:latest
          ports:
            - containerPort: 5000